// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	PostID      uuid.UUID
	UserID      uuid.UUID
	CommentText string
}

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	PostedBy  string
	Body      string
	Likes     int32
	Views     int32
	LikedBy   []string
}

type RefreshToken struct {
	Token      string
	UserID     uuid.UUID
	ExpiryTime time.Time
	CreatedAt  time.Time
}

type Report struct {
	ID         uuid.UUID
	ReportedAt time.Time
	ReportedBy uuid.UUID
	Reason     string
}

type User struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Email            string
	Password         string
	Username         string
	IsPremium        bool
	VerificationCode int32
	IsVerified       bool
}
