name: CI

on:
   pull_request:
      branches: [main]
   
jobs:
   tests:
      name: Tests
      runs-on: ubuntu-latest
      
      steps:
         - name: Check out code
           uses: actions/checkout@v4
         
         - name: Set up Go
           uses: actions/setup-go@v5
           with:
               go-version: '1.23.5'

         - name: Install gosec
           run: go install github.com/securego/gosec/v2/cmd/gosec@latest

         - name: Run gosec
           run: gosec -exclude-dir=internal/database ./...
   
   style:
      name: Style
      runs-on: ubuntu-latest
  
      steps:
        - name: Check out code
          uses: actions/checkout@v4
  
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23.2'
  
        - name: Check formatting
          run: go fmt ./...